# ---------- build stage ----------
# node:20 is used because node-pty 0.10.x (remote shell) needs a NAN-friendly
# toolchain; the image already carries python3/make/g++ for node-gyp.
FROM node:20-bookworm AS builder

WORKDIR /build

# Install deps first so the layer is cached across source edits.
# --omit=optional skips appium (iOS only); the postinstall hook is a no-op then.
COPY package.json package-lock.json .npmrc ./
COPY scripts ./scripts
RUN npm install --omit=optional --no-audit --no-fund

COPY . .
RUN npm run dist:prod

# dist/package.json is generated by webpack and lists only the runtime deps.
WORKDIR /build/dist
RUN npm install --omit=dev --omit=optional --no-audit --no-fund

# ---------- runtime stage ----------
FROM node:20-bookworm-slim

# adb must be on PATH; usbutils/udev help with USB-attached devices.
RUN apt-get update && apt-get install -y --no-install-recommends \
        adb \
        usbutils \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /build/dist ./

ENV WS_SCRCPY_CONFIG=/app/config.yaml \
    ANDROID_HOME=/root/.android

EXPOSE 8000

CMD ["node", "index.js"]
